export const badgeMap: { [key: string]: string } = {
    ':test:': '<img src="/badges/test.png" alt="" class="badge-shadow">', //By SPwins on Deviantart, CC Attribution 3.0 license, gotten from https://www.deviantart.com/spwins/art/Bmo-512x512-883561125
    ':coalition_theater:': '<img src="/badges/coalition_theater.svg" alt="" class="badge">',
    ':fojrp:': '<img src="/badges/fojrp.png" alt="" class="badge">',
    ':dykes_on_bikes:': '<img src="/badges/dykes_on_bikes.png" alt="" class="badge-shadow-w">',
    ':ripple:': '<img src="/badges/ripple.svg" alt="" class="badge invert-dark">',
    ':twitter:': '<img src="/badges/twitter.svg" alt="" class="badge">',
    ':hackrva:': '<img src="/badges/hackrva.svg" alt="" class="badge">',
    ':madrva:': '<img src="/badges/madrva.svg" alt="" class="badge invert-dark">',
    ':sunrise:': '<img src="/badges/sunrise.svg" alt="" class="badge">',
    ':firstfridays:': '<img src="/badges/firstfridays.png" alt="" class="badge-shadow-b">',
    ':kasamacollective:': '<img src="/badges/kasamacollective.svg" alt="" class="badge-shadow-b">',
    ':outpost:': '<img src="/badges/outpost.svg" alt="" class="badge-shadow-b">',
    ':psl:': '<img src="/badges/psl.svg" alt="" class="badge">',
    ':goldlion:': '<img src="/badges/goldlion.svg" alt="" class="badge-shadow-b">',
    ':RVAGrowsGardens1:': '<img src="/badges/RVAGrowsGardens1.svg" alt="" class="badge-shadow-b">',
    ':RVAGrowsGardens2:': '<img src="/badges/RVAGrowsGardens2.svg" alt="" class="badge">',
    ':studiotwothree:': '<img src="/badges/studiotwothree.svg" alt="" class="badge invert-dark">',
    ':BSB:': '<img src="/badges/BSB.svg" alt="" class="badge-shadow-b">',
    ':diversityiridian:': '<img src="/badges/diversityiridian.svg" alt="" class="badge">',
    ':diversitypride:': '<img src="/badges/diversitypride.svg" alt="" class="badge-shadow-b">',
    ':diversityrichmond:': '<img src="/badges/diversityrichmond.svg" alt="" class="badge">',
    ':diversitythrift:': '<img src="/badges/diversitythrift.svg" alt="" class="badge">',
    ':jrabc:': '<img src="/badges/jrabc.svg" alt="" class="badge invert-dark">',
    ':girlspit:': '<img src="/badges/girlspit.svg" alt="" class="badge invert-dark">',
    ':rvalibrary:': '<img src="/badges/rvalibrary.svg" alt="" class="badge-shadow-w">',
    ':layersofchange:': '<img src="/badges/layersofchange.svg" alt="" class="badge">',
    ':transjam:': '<img src="/badges/transjam.svg" alt="" class="badge">',
    ':rva4pal:': '<img src="/badges/rva4pal.svg" alt="" class="badge invert-dark">',
    ':rvapb:': '<img src="/badges/rvapb.svg" alt="" class="badge">',
  };